# Embracing the Magic of NumPy: A Journey into Data Science

## Introduction to NumPy

**By [Mayur Choudhari]**

Hello, fellow data explorers! 🌟 In this notebook, I invite you to dive into the captivating world of NumPy, a fundamental library in Python's data science ecosystem. NumPy's prowess in numerical computations and array manipulations sets the stage for our journey into data science magic.

Throughout this notebook, we'll unravel key NumPy capabilities, witness their applications through code examples, and embark on a quest to wield data with finesse.

**Table of Contents:**
1. Introduction to NumPy
2. Creating and Manipulating 1D Arrays
3. Exploring n-Dimensional Arrays
4. Generating Random Numbers with NumPy
5. Dive into Broadcasting and Mathematical Magic
6. Concluding Thoughts

Feel free to follow along, experiment, and embrace the power of NumPy in your data endeavors.

Let's commence our journey into the realm of arrays, computations, and discovery!


In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])    # created array

In [3]:
arr.shape                    # check the shape

(5,)

In [4]:
print(arr)                   # print array 

[1 2 3 4 5]


In [5]:
a=np.arange(10)             # Create a NumPy array 'a' containing integers from 0 to 9 in sequence.

In [6]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
a=a+2                       # Add 2 to each element in the array 'a' and update the array with the new values.

In [8]:
print(a)

[ 2  3  4  5  6  7  8  9 10 11]


In [9]:
print(a+2)                  # Print the result of adding 2 to each element in the array 'a', without modifying 'a' itself.

[ 4  5  6  7  8  9 10 11 12 13]


In [10]:
print(a)

[ 2  3  4  5  6  7  8  9 10 11]


## Slicing

In [11]:
a[0:8:1]                # Extract a subarray from 'a' starting at index 0, ending at index 7 (8-1), with a step size of 1.

array([2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a[0]

2

# Creating n-dimensional array

In [13]:
a=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11],[12,13,14,15]])

In [14]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
a.shape

(4, 4)

#### Slicing of n-dimensional array

In [16]:
a[0:3,1:3]              # Extract a subarray from 'a' including rows from index 0 to 2 and columns from index 1 to 2

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [17]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### Created new array

In [18]:
a=np.array([[0,1,2],[4,5,6],[8,9,10],[12,13,14]])

In [19]:
a

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [20]:
a=a.T                  # Transpose the array 'a', swapping rows and columns.

In [21]:
a

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14]])

In [22]:
a.reshape(4,3)          # reshape the array

array([[ 0,  4,  8],
       [12,  1,  5],
       [ 9, 13,  2],
       [ 6, 10, 14]])

## Creating  Random

In [23]:
np.random.random()

0.10744068708110388

In [24]:
np.random.random(10) # it will create 10 random value

array([0.9121749 , 0.16160872, 0.6466919 , 0.11873428, 0.20824179,
       0.69502368, 0.70578586, 0.59701521, 0.80091541, 0.01493642])

#### Seed:-

**The seed value in NumPy's random module is used to initialize the random number generator, ensuring that the same sequence of random numbers can be reproduced when the same seed is used.**

In [25]:
np.random.seed(10)                              
print(np.random.random()) # Set the random seed to ensure reproducibility,& generate and print a random number between 0 and 1.

0.771320643266746


##### Creating randint

In [26]:
np.random.randint(low=5,high=7,size=6)        # Generate an array of 6 random integers between 5 and 7.

array([5, 6, 5, 6, 6, 5])